data_folder: "/mnt/cpfs-data/scripts/train/empdata/DCKS-dataset"
model_checkpoint_folder: "model_checkpoint"
model_save_folder: "model_save"
history_length: 10
comet_model_path: "/mnt/cpfs-data/scripts/train/empdata/model_checkpoint/comet-atomic_2020_BART"
bert_model_path: "/mnt/cpfs-data/scripts/train/empdata/model_checkpoint/bert-base"
mpnet_model_path: "/mnt/cpfs-data/scripts/train/empdata/model_checkpoint/mpnet-base"
bart_model_path: "/mnt/cpfs-data/scripts/train/empdata/model_checkpoint/bart-base"
ranking_model_path: "/mnt/cpfs-data/scripts/train/empdata/DCKS-entity_ranking_model_context_0.19263948602829037"
device: "cuda:0"
social_knowledge_file_name:
  train: "DCKS_train_comet_social.pkl"
  test: "DCKS_test_comet_social.pkl"
entity_knowledge_file_name:
  train: "DCKS_train_comet_entity.pkl"
  test: "DCKS_test_comet_entity.pkl"

